### ISSUE TITLE
About extractors

### ISSUE THREAD

**Issue by Yguang0419** [scu-zjz/IMDLBenCo#20]
Looking forward to noiseprint++

**Comment by SunnyHaze** [comment]
Thank you for your attention to our work and for this great suggestion! We are currently focused on testing all major functions and going to release them. After that, we will start working on implementing this feature extractor.

**Comment by SunnyHaze** [comment]
Hi, Noiseprint++ can be found here: https://github.com/scu-zjz/IMDLBenCo/tree/main/IMDLBenCo/model_zoo/trufor
