### ISSUE TITLE
如何运行别的数据集

### ISSUE THREAD

**Issue by zhouhao028** [scu-zjz/IMDLBenCo#45]
作者，您好！ 首先十分感谢你的工作。我有一个问题想要请教您，请问如何加载自己所创建的数据集，并使用这是模型进行训练和测试，以及我看了新手教程对怎么运用还是有些不懂。十分感谢，您的帮助！！！

**Comment by SunnyHaze** [comment]
你好，感谢你对我们工作的关注。

首先需要使用`pip install imdlbenco`在python环境中安装。


参考帮助文档中[数据集准备](https://scu-zjz.github.io/IMDLBenCo-doc/zh/guide/quickstart/0_dataprepare.html)，按照相应格式准备好数据集。ManiDataset就是CASIA数据集的格式，稍微修改文件名就可以load，JSONDATASET就是一个二维数组，每一条是一个Image mask pair的路径。

然后如果你需要复现模型，请使用`benco init model_zoo`，就可以看到生成了所需要的所有脚本。

选择你需要的训练脚本，比如`demo_train_mvss.sh`这个是训练MVSS的脚本，修改其中的`data_path`和`test_data_path`字段为你期望的训练集和测试集。可能也需要根据你的显卡数量和可用显卡编号修改其他训练参数。然后根据[Model_zoo教程](https://scu-zjz.github.io/IMDLBenCo-doc/zh/guide/quickstart/2_model_zoo.html#%E9%80%9A%E8%BF%87benco-init%E5%88%9D%E5%A7%8B%E5%8C%96)末尾的指令运行即可。

如果还有其他问题，欢迎及时讨论。

**Comment by zhouhao028** [comment]
![1](https://github.com/user-attachments/assets/378c353e-c3fd-4849-ab17-4608f738283d)
![2](https://github.com/user-attachments/assets/b69e3f91-f31e-428b-ac98-bc69a807d1e3)
 您好，感谢你的帮助！ 我已经按照您提供的方法进行了复现，但它还是无法识别我的数据集，我将我自己的数据集上传到IMDLBenCo的目录下与您说的(安装好benco后，创建一个干净的空文件夹)同级，然后，我将要训练的模型(.sh)修改了其中的data_path和test_data_path(这是我的调用 --data_path "/data0/zh/IMDLBenCo/IMDLBenCo/Doc" \ 以及 --test_data_path "/data0/zh/IMDLBenCo/IMDLBenCo/Doc-Test") 发现无法识别。再次麻烦您了！

**Comment by SunnyHaze** [comment]
请问报什么错呢？

**Comment by SunnyHaze** [comment]
而且benco理论上说是不需要clone仓库的方式进行使用的，只需要使用命令行生成的脚本即可，目测你是clone了仓库进行使用？

**Comment by zhouhao028** [comment]
我是在github上面下载 然后将其放到服务器上面 然后按照您和我说的运行这个是报错内容

**Comment by zhouhao028** [comment]
我是在github上面下载 然后将其放到服务器上面 然后按照您和我说的运行这个是报错内容

![Uploading 屏幕截图 2024-10-21 222145.png…]()

**Comment by zhouhao028** [comment]
我是在github上面下载 然后将其放到服务器上面 然后按照您和我说的运行。这个是报错内容
![1](https://github.com/user-attachments/assets/700aa038-5d77-4ef7-984e-fe63eb066615)

**Comment by SunnyHaze** [comment]
你好，这个报错与Benco没有关系，是你当前的设备没有安装GPU版本的Pytorch导致的。

**Comment by zhouhao028** [comment]
好的，麻烦了！十分感谢

**Comment by zhouhao028** [comment]
您好，我安装了GPU版本的Pytorch之后 还是会发生报错。  具体原因是找不到路径 但我的文件和指导说明一致
![1](https://github.com/user-attachments/assets/bb2df853-3e99-40e1-91fc-780c2207a3fb)
![2](https://github.com/user-attachments/assets/f0e1a1c1-1e3b-46a4-aba5-890ab723dca7)

**Comment by SunnyHaze** [comment]
你的运行指令和当前“工作路径”是什么呢？

目测因为train.py不会在runs/路径下，所以找不到，相对路径需要保证和runs下的sh相协调，请检查

**Comment by zhouhao028** [comment]
![1](https://github.com/user-attachments/assets/2633765f-ff36-41d7-a1f8-50d2c967b371)
您好，我的工作路径为zh@amax:/data0/zh/IMDLBenCo/IMDLBenCo/work  运行指令为sh "/data0/zh/IMDLBenCo/IMDLBenCo/work/runs/demo_train_mantra_net.sh"  我使用了绝对路径

**Comment by SunnyHaze** [comment]
`demo_train_mantra_net.sh`中的内容应该是索引到工作路径的`./train.py`下，但是你上面的报错中是：`data0/zh/IMDLBenco/IMDLBenco/work/runs/./train.py`，好像工作路径是子路径“runs”下面？

如果还是有问题请尝试用相对路径试试？

**Comment by zhouhao028** [comment]
您好，我按照您说的相对路径测试了,还是报错,识别不到路径。我使用了zh@amax:/data0/zh/IMDLBenCo/IMDLBenCo/work$ sh ./runs/demo_train_mantra_net.sh。 按照文档所提示的内容,假设我要训练所需的模型，我应该在新创建的工作文件夹下(/data0/zh/IMDLBenCo/IMDLBenCo/work)调用sh ./runs/demo_XXXX_XXXX.sh。但我使用了绝对和相对路径都发生报错。

**Comment by zhouhao028** [comment]
作者，您好！我已经发送邮件到您提供的邮箱。
