### ISSUE TITLE
img 和 mask 大小不一致

### ISSUE THREAD

**Issue by wxm000000** [scu-zjz/IMDLBenCo#48]
您好，我想使用 cat-net 运行 OpenForensics 数据集，首先我修改了这部分，
![截图 2024-10-23 22-01-57](https://github.com/user-attachments/assets/ae7dde63-ae02-4789-b5a3-b46835894be0)

然后我发现他提示 img 和 mask 的大小不一致
![截图 2024-10-23 22-03-30](https://github.com/user-attachments/assets/911dd253-5a1c-45f1-90eb-e469400ee0ed)

似乎 img 和 mask 也没有一一对应，这是我打印出来的结果
![截图 2024-10-23 22-04-25](https://github.com/user-attachments/assets/695f25d0-d04e-44f9-be1b-93ecad48942f)

请问这个该怎么解决呢？

谢谢您！

**Comment by SunnyHaze** [comment]
请问你是传入的文件夹路径，还是通过json的方式组织的数据集？

**Comment by wxm000000** [comment]
解决了，有点尴尬，是我的数据集本身有点问题。

**Comment by SunnyHaze** [comment]
没事，解决了就好！Case closed!
